name: Type checking.

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [ '3.10' ]
    timeout-minutes: 3
    steps:
      - name: Checkout code.
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-versions }}.
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install mypy

      - name: Validate function returns and args.
        run: |
          mypy \
          Python_Skeletons_and_Tests/1ArraysStrings/rotate_matrix_7.py
          Python_Skeletons_and_Tests/2LinkedLists/linked_list.py
          Python_Skeletons_and_Tests/2LinkedLists/remove_duplicates_1.py
          Python_Skeletons_and_Tests/2LinkedLists/reverse.py
