name: Verify Python code quality with pylint.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [ '3.10' ]
    steps:
      - name: Checkout code.
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-versions }}.
        uses: actions/setup-python@v3
        with:
          python-versions: ${{ matrix.python-versions }}

      - name: Install dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Analyze code with pylint.
        run: |
          echo 'Files to be linted:'
          echo $(git ls-files '*.py')
          pylint -v \
          --rcfile=Python_Skeletons_and_Tests/.pylint_configuration/.pylintrc \
          $(git ls-files '*.py')
